## makefile automates the build and deployment for python projects

# type of project
PROJ_TYPE=	python
# make modules to add functionality to a build
#PROJ_MODULES=	docker release model

# edit these if you want
#GITUSER=	johndoe
#PYPI_USER=	johndoe
#PYPI_SIGN=	johndoe@example.com

# additional resources generated by the build that should be cleaned up
#ADD_CLEAN+=

# make build dependencies
_ :=	$(shell [ ! -d .git ] && git init ; [ ! -d zenbuild ] && \
	  git submodule add https://github.com/plandes/zenbuild && make gitinit )

include ./zenbuild/main.mk
